config/routes.rb
Rails.application.routes.draw do
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  #CREATED BY DEVISE
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  #CREATED BY DAN
  resources :posts do
    resources :post_mentioned_users
  end
  resources :users
  #CREATED BY LOWELL
  get '/patients/json', to: 'prescriptions#prescription_json'
  resources :events
  resources :doctors do
    resources :prescriptions, except: [:index, :new, :create, :edit, :update, :destroy]
  end
  resources :prescriptions, only: [:index, :new, :create, :edit, :update, :destroy]
  #CREATED BY ISAAC
    # Tasks routes/tasks_assigned_users nested routes
  resources :tasks, except: [:new] do
    member do
      patch :complete
    end
    resources :tasks_assigned_users, shallow: true
  end

  # Route to generate prescriptions csv download for client
  resources :prescriptions do
    collection { get :download }
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="d-navbar">
  <ul class="sidebar">
    <li class="d-flex flex-column align-items-center">
      <%= link_to root_path do %>
        <i class='fa-solid fa-house home' style='color: #d9d9d9;'></i>
      <% end %>
      <p>Home</p>
    </li>
    <li class="d-flex flex-column align-items-center">
      <%= link_to posts_path do %>
        <i class='fa-solid fa-message' style='color: #d9d9d9;'></i>
      <% end %>
      <p>Posts</p>
    </li>
    <li class="d-flex flex-column align-items-center">
      <%= link_to tasks_path do %>
        <i class='fa-solid fa-list-check' style='color: #d9d9d9;'></i>
      <% end %>
      <p>Tasks</p>
    </li>
    <li class="d-flex flex-column align-items-center">
      <%= link_to events_path do %>
        <i class='fa-solid fa-calendar-days' style='color: #d9d9d9;'></i>
      <% end %>
      <p>Events</p>
    </li>
    <li class="d-flex flex-column align-items-center">
      <%= link_to doctors_path do %>
        <i class='fa-solid fa-user-doctor' style='color: #d9d9d9;'></i>
      <% end %>
      <p>Doctors</p>
    </li>
    <li class="d-flex flex-column align-items-center">
      <%= link_to prescriptions_path do %>
        <i class='fa-solid fa-file' style='color: #d9d9d9;'></i>
      <% end %>
      <p>Meds</p>
    </li>
    <li class="d-flex flex-column align-items-center">
      <%= link_to destroy_user_session_path, data: {turbo_method: :delete} do %>
        <i class='fa-solid fa-right-from-bracket' style='color: #d9d9d9;'></i>
      <% end %>
      <p>Logout</p>
    </li>
  </ul>
</div>

app/views/shared/_typedjs.html.erb
<script>
  var typed = new Typed(`<%= element %>`, {
    strings: [`<%= message %>,`, `Don't forget to check your pending tasks.`],
    typeSpeed: <%= speed %>
  });
</script>

app/views/shared/_wagon_navbar.html.erb
<div class="navbar d-navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>