config/routes.rb
Rails.application.routes.draw do
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  #CREATED BY DEVISE
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  #CREATED BY DAN
  resources :posts do
    resources :post_mentioned_users
  end
  resources :users
  #CREATED BY LOWELL
  get '/patients/json', to: 'prescriptions#prescription_json'
  resources :events
  resources :doctors do
    resources :prescriptions, except: [:index, :new, :create, :edit, :update, :destroy]
  end
  resources :prescriptions, only: [:index, :new, :create, :edit, :update, :destroy]
  #CREATED BY ISAAC
    # Tasks routes/tasks_assigned_users nested routes
  resources :tasks, except: [:new] do
    member do
      patch :complete
    end
    resources :tasks_assigned_users, shallow: true
  end

  # Route to generate prescriptions csv download for client
  resources :prescriptions do
    collection { get :download }
  end
end

app/models/event.rb
class Event < ApplicationRecord
  EVENTTYPES = ["Doctor Appointment", "Physical Therapy", "Guest in Town", "Other"]
  belongs_to :user
  has_many :event_invited_users
  has_many :invited_users, through: :event_invited_users, source: :user # this is the user's invited events
  has_many :medical_appointments
  has_many :doctors, through: :medical_appointments
  validates :event_type, inclusion: { in: EVENTTYPES }
  validates :start, :end, presence: true

  def owner
    self.user
  end

  def start_time
    self.start ##Where 'start' is a attribute of type 'Date' accessible through MyModel's relationship
  end
  
  def end_time
    self.end ##Where 'start' is a attribute of type 'Date' accessible through MyModel's relationship
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:destroy]

  def index
    # Scope your query to the dates being shown:
    start_date = params.fetch(:start_date, Date.today).to_date
    @events = Event.where(start: start_date.beginning_of_month.beginning_of_week..start_date.end_of_month.end_of_week)
    @event = Event.new
    @event_notifications = current_user.event_invited_users.order(created_at: :desc).limit(5)
    @recent_events_count = Event.where('created_at > ?', 48.hours.ago).count
  end

  def show
    @event = Event.find(params[:id])
    # only call strong params when creating and updating
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user
    if @event.save!
      redirect_to events_path, alert: "your event was created"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    @event.update(event_params)
    redirect_to events_path
  end

  def destroy
    @event.destroy
    redirect_to events_path, alert: "your event was deleted"
  end

  private

  def event_params
    params.require(:event).permit(:id, :event_type, :start, :end, :title, :location, :user_id)
  end

  def set_event
    @event = Event.find(params[:id])
  end
end

app/views/events/_edit_event_modal.html.erb
<button class="text-nowrap bd-highlight text-truncate event-block" type="button" data-bs-toggle="modal" data-bs-target="#exampleModal<%= event.id %>">
  <div><%= event.start.strftime("%l:%M %P") %> <%= event.title %></div>
</button>
<div class="modal fade" id="exampleModal<%= event.id %>" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="exampleModal<%= event.id %>Label" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModal<%= event.id %>Label">Edit Event</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <%= form_for event, data: { turbo: false } do |f| %>
        <div class="modal-body">
          <div class="event-input">
            <%= f.label :title, class:"form-title-label" %>
            <%= f.text_field :title, class: "form-control" %>
          </div>
          <div class="event-input">
            <%= f.label :event_type, class:"form-title-label" %>
            <%= f.select :event_type, Event::EVENTTYPES, class: "form-select" %>
          </div>
          <div class="event-input">
            <%= f.label :start, class:"form-title-label" %>
            <%= f.datetime_field :start %>
          </div>
          <div class="event-input">
            <%= f.label :end, class:"form-title-label" %>
            <%= f.datetime_field :end %>
          </div>
          <div class="event-input">
            <%= f.label :location, class:"form-title-label" %>
            <%= f.text_field :location, class: "form-control" %>
          </div>
        </div>
        <div class="modal-footer d-flex flex-row">
          <button type="button" class="btn btn-primary-doctor" data-bs-dismiss="modal">Close</button>
          <%= link_to "Delete Event", event_path(event), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this event?" }, class: "btn btn-primary-doctor" %>
          <%= f.submit "Save changes", class: "btn btn-primary-doctor" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/events/_event-form.html.erb
<div>
<%= form_for @event do |f| %>
  <div>
  <%= f.label :title %>
  <%= f.text_field :title %>
  </div>

  <div>
  <%= f.label :event_type %>
  <%= f.select :event_type, Event::EVENTTYPES %>
  </div>

  <div>
  <%= f.label :start %>
  <%= f.datetime_field :start %>
  </div>

  <div>
  <%= f.label :end %>
  <%= f.datetime_field :end %>
  </div>

  <div>
  <%= f.label :location %>
  <%= f.text_field :location %>
  </div>

  <div>
  <%= f.submit %>
  </div>
<% end %>
</div>

app/views/events/_modal.html.erb
<!-- Trigger Button for Modal -->
<div class="col-md-2 add-doctor-button">
  <button type="button" class="btn btn-primary-event" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
    Create Event
  </button>
</div>
<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel"><span class="post-module-header-one">Create </span> <span class="post-module-header">event</span></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <%= form_for @event do |f| %>
        <div id="event-form-container" class="modal-body">
          <div class="event-input">
            <%= f.label :title, class:"form-title-label" %>
            <%= f.text_field :title, class: "form-control" %>
          </div>
          <div class="event-input">
            <%= f.label :event_type, class:"form-title-label" %>
            <%= f.select :event_type, Event::EVENTTYPES, class: "form-select" %>
          </div>
          <div class="event-input">
            <%= f.label :start, class:"form-title-label" %>
            <%= f.datetime_field :start %>
          </div>
          <div class="event-input">
            <%= f.label :end, class:"form-title-label" %>
            <%= f.datetime_field :end %>
          </div>
          <div class="event-input">
            <%= f.label :location, class:"form-title-label" %>
            <%= f.text_field :location, class: "form-control" %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary-doctor">Create</button>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/events/destroy.html.erb
<h1>Event#destroy</h1>
<p>Find me in app/views/event/destroy.html.erb</p>

app/views/events/edit.html.erb
<div>
<h1>Edit <%= @event.title %></h1>
<%= render "event-form", event: @event %>
<h3><%= link_to "Delete Event", event_path(@event), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this event?" } %>
</h3>
</div>

app/views/events/index.html.erb
<div class="container d-con">
  <div class= "logo-row">
    <div class="col-4 user-row">
      <p id="date" class="date"></p>
      <script>
        var today = new Date();
        document.getElementById("date").innerHTML = today.toDateString();
      </script>
    </div>
    <div class="col-4">
      <p class="user">Welcome back, <%= current_user.first_name %>.</p>
    </div>
    <div class="col-4 logo-box">
      <img src="https://res.cloudinary.com/dqe5h0j32/image/upload/v1687795741/Care_Team_Logo_Updated_azhxg4.svg" class="logo" alt="">
    </div>
  </div>
  <div class="row calendar-manager">
    <div class="d-flex justify-content-between">
      <h1>Calendar</h1>
      <div><%= render "modal", event: @event %></div>
    </div>
  </div>
  <div class="row d-flex">
    <div id="calendar" class="calendar-large">
      <%= turbo_frame_tag 'calendar' do %>
        <%= month_calendar(events: @events) do |date, events| %>
          <%= date.day %>
          <% events.each do |event| %>
            <div>
              <%= render "edit_event_modal", event: event %>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
    <div class="calendar-side">
      <!-- Insert first calendar-side card here -->
      <div class="card text-bg mb-3 first-card" style="max-width: 100%;">
        <div class="card-header"><strong>Events Notifications</strong></div>
        <div class="card-body">
          <h5 class="card-title">Upcoming Events:</h5>
          <% @events.first(2).each do |event| %>
            <li class="welcome-text-notification"><%= event.title %> on <%= event.start.strftime("%A, %B %d, %Y") %></li>
          <% end %>
          <br>
          <br>
          <br>
          <p style="font-size: 14px;">Events created in the last 48 hours: <%= @recent_events_count %></p>
        </div>
      </div>
      <!-- First calendar-side card ends here -->
      <!-- Second calendar-side card ends here -->
      <div class="card border second-card mb-3" style="max-width: 100%;">
        <div class="card-header"><strong>All Events</strong></div>
        <div class="card-body-two text-secondary">
          <% @events.each do |event| %>
            <div class="row event-row d-flex">
              <div class="col-1 avatar-event-box">
                <%= image_tag(event.owner.avatar, class: "avatar-event-icon") if event.owner.avatar.attached? %>
              </div>
              <div class ="col-9 post-details-mini">
                <ul>
                  <li class="task-details" style="font-size: 14px; color: #a9a9a9;"><strong><%= event.title %></strong></li>
                  <span class="post-content">
                    <% unless event.notes.nil? %>
                      <%= event.notes.split(" ").length > 9 ? event.notes.split(" ")[0...9].join(" ") + '...' : event.notes %>
                    <% end %>
                  </span>
                  <li class="time-ago"><em><%= time_ago_in_words_custom(event.created_at) %></em></li>
                </ul>
              </div>
              <div class="col-1 post-arrow">
                <%= link_to edit_event_path(event) do %>
                  <i class="fa fa-arrow-right" style="color: #b792fc;"></i>
                <% end %>
              </div>
            </div>
          <% end %>        </div>
      </div>
    </div>
  </div>
</div>
</div>

app/views/events/new.html.erb
<h1>Create a New Event</h1>
<%= render "event-form", event: @event %>

app/views/events/show.html.erb
<h1>Event#show</h1>
<p>Find me in app/views/event/show.html.erb</p>